[2025-07-25T09:58:44.450+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T09:58:44.529+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T08:00:00+00:00 [queued]>
[2025-07-25T09:58:44.558+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T08:00:00+00:00 [queued]>
[2025-07-25T09:58:44.563+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T09:58:44.623+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 08:00:00+00:00
[2025-07-25T09:58:44.649+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=661) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T09:58:44.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test', 'load_user_dim_table', 'scheduled__2025-07-25T08:00:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpvexaq4d5']
[2025-07-25T09:58:44.663+0000] {standard_task_runner.py:105} INFO - Job 42: Subtask load_user_dim_table
[2025-07-25T09:58:44.652+0000] {standard_task_runner.py:72} INFO - Started process 674 to run task
[2025-07-25T09:58:44.849+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T08:00:00+00:00 [running]> on host 72bd964f8e11
[2025-07-25T09:58:45.056+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T08:00:00+00:00'
[2025-07-25T09:58:45.059+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T09:58:45.122+0000] {my_dags.py:343} INFO - Loading user dimension table
[2025-07-25T09:58:45.127+0000] {my_dags.py:363} INFO - Inserted 0 records into users table
[2025-07-25T09:58:45.129+0000] {my_dags.py:366} INFO - User dimension table loaded successfully
[2025-07-25T09:58:45.130+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T09:58:45.566+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T09:58:45.568+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test, task_id=load_user_dim_table, run_id=scheduled__2025-07-25T08:00:00+00:00, execution_date=20250725T080000, start_date=20250725T095844, end_date=20250725T095845
[2025-07-25T09:58:45.672+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T09:58:45.700+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
