[2025-07-26T09:10:47.557+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T09:10:47.615+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T10:00:00+00:00 [queued]>
[2025-07-26T09:10:47.644+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T10:00:00+00:00 [queued]>
[2025-07-26T09:10:47.647+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-26T09:10:47.705+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 10:00:00+00:00
[2025-07-26T09:10:47.729+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T09:10:47.733+0000] {standard_task_runner.py:72} INFO - Started process 270 to run task
[2025-07-26T09:10:47.729+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test', 'load_user_dim_table', 'scheduled__2025-07-25T10:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpaf910fcz']
[2025-07-26T09:10:47.742+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask load_user_dim_table
[2025-07-26T09:10:48.019+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test.load_user_dim_table scheduled__2025-07-25T10:00:00+00:00 [running]> on host 72bd964f8e11
[2025-07-26T09:10:48.901+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-25T10:00:00+00:00'
[2025-07-26T09:10:48.905+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-26T09:10:48.988+0000] {my_dags.py:297} INFO - Loading user dimension table
[2025-07-26T09:10:49.010+0000] {my_dags.py:317} INFO - Inserted 0 records into users table
[2025-07-26T09:10:49.018+0000] {my_dags.py:320} INFO - User dimension table loaded successfully
[2025-07-26T09:10:49.020+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T09:10:49.053+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-26T09:10:49.060+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test, task_id=load_user_dim_table, run_id=scheduled__2025-07-25T10:00:00+00:00, execution_date=20250725T100000, start_date=20250726T091047, end_date=20250726T091049
[2025-07-26T09:10:49.149+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T09:10:49.246+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-26T09:10:49.252+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
