[2025-07-26T09:51:46.238+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T09:51:46.278+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test2.create_tables manual__2025-07-26T09:51:44.063386+00:00 [queued]>
[2025-07-26T09:51:46.299+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test2.create_tables manual__2025-07-26T09:51:44.063386+00:00 [queued]>
[2025-07-26T09:51:46.300+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-26T09:51:46.329+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_tables> on 2025-07-26 09:51:44.063386+00:00
[2025-07-26T09:51:46.344+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=661) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T09:51:46.347+0000] {standard_task_runner.py:72} INFO - Started process 662 to run task
[2025-07-26T09:51:46.343+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test2', 'create_tables', 'manual__2025-07-26T09:51:44.063386+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmphxuncx3w']
[2025-07-26T09:51:46.349+0000] {standard_task_runner.py:105} INFO - Job 18: Subtask create_tables
[2025-07-26T09:51:46.495+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test2.create_tables manual__2025-07-26T09:51:44.063386+00:00 [running]> on host 2f3d4b2b9190
[2025-07-26T09:51:46.636+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test2' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T09:51:44.063386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T09:51:44.063386+00:00'
[2025-07-26T09:51:46.639+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-26T09:51:46.695+0000] {my_dags.py:368} INFO - All tables created successfully
[2025-07-26T09:51:46.697+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T09:51:46.715+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-26T09:51:46.716+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test2, task_id=create_tables, run_id=manual__2025-07-26T09:51:44.063386+00:00, execution_date=20250726T095144, start_date=20250726T095146, end_date=20250726T095146
[2025-07-26T09:51:46.769+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T09:51:46.821+0000] {taskinstance.py:3895} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-07-26T09:51:46.825+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
