[2025-07-25T10:06:50.179+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-25T10:06:50.220+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table manual__2025-07-25T10:06:44.994705+00:00 [queued]>
[2025-07-25T10:06:50.243+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test.load_user_dim_table manual__2025-07-25T10:06:44.994705+00:00 [queued]>
[2025-07-25T10:06:50.245+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-25T10:06:50.284+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-25 10:06:44.994705+00:00
[2025-07-25T10:06:50.306+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1149) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-25T10:06:50.309+0000] {standard_task_runner.py:72} INFO - Started process 1150 to run task
[2025-07-25T10:06:50.304+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test', 'load_user_dim_table', 'manual__2025-07-25T10:06:44.994705+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmpmz1huyxi']
[2025-07-25T10:06:50.311+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask load_user_dim_table
[2025-07-25T10:06:50.485+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test.load_user_dim_table manual__2025-07-25T10:06:44.994705+00:00 [running]> on host 72bd964f8e11
[2025-07-25T10:06:50.704+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-25T10:06:44.994705+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-25T10:06:44.994705+00:00'
[2025-07-25T10:06:50.707+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-25T10:06:50.765+0000] {my_dags.py:333} INFO - Loading user dimension table
[2025-07-25T10:06:50.769+0000] {my_dags.py:353} INFO - Inserted 0 records into users table
[2025-07-25T10:06:50.770+0000] {my_dags.py:356} INFO - User dimension table loaded successfully
[2025-07-25T10:06:50.772+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-25T10:06:51.123+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-25T10:06:51.126+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test, task_id=load_user_dim_table, run_id=manual__2025-07-25T10:06:44.994705+00:00, execution_date=20250725T100644, start_date=20250725T100650, end_date=20250725T100651
[2025-07-25T10:06:51.211+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-25T10:06:51.230+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
