[2025-07-26T09:57:05.207+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-26T09:57:05.269+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_test2.load_time_dim_table manual__2025-07-26T09:51:44.063386+00:00 [queued]>
[2025-07-26T09:57:05.304+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_test2.load_time_dim_table manual__2025-07-26T09:51:44.063386+00:00 [queued]>
[2025-07-26T09:57:05.307+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-07-26T09:57:05.347+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_time_dim_table> on 2025-07-26 09:51:44.063386+00:00
[2025-07-26T09:57:05.365+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1036) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-26T09:57:05.368+0000] {standard_task_runner.py:72} INFO - Started process 1039 to run task
[2025-07-26T09:57:05.364+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_postgres_test2', 'load_time_dim_table', 'manual__2025-07-26T09:51:44.063386+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/my_dags.py', '--cfg-path', '/tmp/tmps4ixt_7z']
[2025-07-26T09:57:05.370+0000] {standard_task_runner.py:105} INFO - Job 43: Subtask load_time_dim_table
[2025-07-26T09:57:05.486+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_test2.load_time_dim_table manual__2025-07-26T09:51:44.063386+00:00 [running]> on host 2f3d4b2b9190
[2025-07-26T09:57:05.650+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_postgres_test2' AIRFLOW_CTX_TASK_ID='load_time_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-26T09:51:44.063386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-26T09:51:44.063386+00:00'
[2025-07-26T09:57:05.653+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-26T09:57:05.701+0000] {my_dags.py:626} INFO - Loading time dimension table
[2025-07-26T09:57:05.787+0000] {my_dags.py:650} INFO - Inserted 6813 records into time table
[2025-07-26T09:57:05.792+0000] {my_dags.py:653} INFO - Time dimension table loaded successfully
[2025-07-26T09:57:05.794+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-07-26T09:57:05.817+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-26T09:57:05.819+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_postgres_test2, task_id=load_time_dim_table, run_id=manual__2025-07-26T09:51:44.063386+00:00, execution_date=20250726T095144, start_date=20250726T095705, end_date=20250726T095705
[2025-07-26T09:57:05.869+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-07-26T09:57:05.908+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-26T09:57:05.911+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
